# Generated by Django 4.1.3 on 2022-11-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ingredints',
            name='recipeId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.recipes'),
        ),
        migrations.AddField(
            model_name='ingredints',
            name='supplierId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.supplier'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='orderDetailsId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.orderdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryAgentId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.deliveryagent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderDetailId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.orderdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='staffId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='menuItemId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='emailaddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='homeAddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='shoppingcart.category'),
        ),
    ]
