# Generated by Django 4.1.3 on 2022-11-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_category_ingredints_recipeid_ingredints_supplierid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredints',
            new_name='Ingredint',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
