# Generated by Django 4.1.3 on 2022-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_rename_ingredints_ingredint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='orderDetailsId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryAgentId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDetailId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staffId',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='Order', to='shoppingcart.menuitem'),
        ),
    ]
