# Generated by Django 4.1.3 on 2022-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_remove_menuitem_orderdetailsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='MenuItem', to='shoppingcart.category'),
        ),
    ]
