# Generated by Django 4.1.3 on 2022-11-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingcart', '0006_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='orderDetailsId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.orderdetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryAgentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.deliveryagent'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderDetailId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.orderdetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='staffId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emailaddress',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userPassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredint',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='totalAmount',
            field=models.FloatField(),
        ),
    ]
