# Generated by Django 4.1.3 on 2022-11-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_customer_user_menuitem_orderdetailsid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='orderDetailsId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDetailId',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderID',
        ),
        migrations.AddField(
            model_name='order',
            name='transactionId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='menuItemId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.menuitem'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredint',
            name='recipeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredint',
            name='supplierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryAgentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.deliveryagent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='staffId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='totalAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menuItemId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.menuitem'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.order'),
        ),
    ]
