# Generated by Django 4.1.3 on 2022-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_remove_menuitem_orderdetailsid_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredint',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
