# Generated by Django 4.1.3 on 2022-11-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_remove_menuitem_orderdetailsid_remove_order_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerId',
            new_name='customer',
        ),
    ]
