# Generated by Django 4.1.3 on 2022-11-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0009_rename_customerid_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
