# Generated by Django 4.1.3 on 2022-11-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_rename_menuitemid_orderdetail_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='menuItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.order'),
        ),
    ]
