# Generated by Django 4.1.3 on 2022-12-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0009_alter_ingredint_price_alter_menuitem_price_and_more'),
        ('shoppingcart', '0012_alter_orderdetail_menuitem_alter_orderdetail_order'),
    ]

    operations = [
    ]
