# Generated by Django 4.1.3 on 2022-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0013_merge_20221205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
