# Generated by Django 4.1.3 on 2022-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_alter_order_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
