# Generated by Django 4.1.3 on 2022-12-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_alter_order_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userPassword',
        ),
    ]
