# Generated by Django 4.1.3 on 2022-12-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
