# Generated by Django 4.1.3 on 2022-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0016_remove_customer_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
